### ISSUE TITLE
Can't remove cgroup freeze directory

### ISSUE THREAD

**Issue by DavidBuchanan314** [DavidBuchanan314/dlinject#2]
https://github.com/DavidBuchanan314/dlinject/blob/master/dlinject.py#L256

```
Traceback (most recent call last):
  File "./dlinject.py", line 283, in <module>
    dlinject(args.pid, args.lib_path, args.stopmethod or "sigstop")
  File "./dlinject.py", line 258, in dlinject
    os.rmdir(freeze_dir)
OSError: [Errno 16] Device or resource busy: '/sys/fs/cgroup/freezer/dlinject_19dc059e2ea46b80'
```
I believe this fails because the `/tasks` file still has a running process in. I guess I need to figure out how to remove tasks.

**Comment by DavidBuchanan314** [comment]
Fixed in 9739ece1a7a284227ef5e843821deae2e3b51ff4
